openapi: 3.0.0
info:
  title: LetterBox
  version: '1.0'
  description: LetterBoxで用いるAPIの仕様書
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/stores:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
              examples: {}
      operationId: get-api-v1-stores
      parameters:
        - schema:
            type: integer
            example: 50
            minimum: 0
            maximum: 100
          in: query
          name: count
          description: 件数を指定する
      description: 店舗一覧を返すエンドポイント
  /api/v1/stores/search:
    get:
      summary: Your GET endpoint
      tags:
        - stores
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
              examples:
                no data:
                  value:
                    message: No data
                sample:
                  value:
                    message: success
                    data:
                      - id: 1
                        name: sample
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: get-store-id
      description: 店舗を検索する
      parameters:
        - schema:
            type: string
            example: sample
          in: query
          name: keyword
          required: true
          description: 店舗検索の際に利用するキーワード
  /api/v1/employees/search:
    get:
      summary: Your GET endpoint
      tags:
        - employees
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  store_id:
                    type: integer
                  employees:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        first_name:
                          type: string
                        last_name:
                          type: string
              examples:
                example-1:
                  value:
                    store_id: 0
                    employees:
                      - id: 0
                        first_name: string
                        last_name: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: no data
      operationId: 'get-employees-storeId]'
      description: お店に所属する従業員の一覧を返す
      parameters:
        - schema:
            type: integer
            example: 1
          in: query
          name: store_id
          description: store_idを指定する
          required: true
    parameters: []
  /api/v1/messages:
    post:
      summary: ''
      operationId: post-messages
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: success
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: failure
      parameters:
        - schema:
            type: integer
          in: query
          name: store_id
          description: 店舗ID
        - schema:
            type: integer
          in: query
          name: employee_id
          description: 従業員ID
        - schema:
            type: string
          in: query
          name: message
          description: メッセージ
      tags:
        - messages
      description: メッセージを投稿する
    parameters: []
    get:
      summary: ''
      operationId: get-api-v1-messages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        message:
                          type: string
                        created_at:
                          type: string
      description: 店舗一覧を返すエンドポイント
      parameters:
        - schema:
            type: number
          in: query
          name: employee_id
          description: 従業員IDを指定する。これがある場合は、従業員IDに紐付いたメッセージのみを返す。
  /api/v1/login/employees:
    post:
      summary: ''
      operationId: post-api-v1-login
      responses:
        '200':
          description: OK
      description: 従業員アカウントの認証をする場合に使用するエンドポイント
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                password:
                  type: string
              required:
                - login_id
                - password
    parameters: []
  /api/v1/login/stores:
    post:
      summary: ''
      operationId: post-api-v1-stores-login
      responses:
        '200':
          description: OK
      description: 店舗アカウントを認証する際に使用するエンドポイント
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                password:
                  type: string
              required:
                - login_id
                - password
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
  responses: {}
tags:
  - name: employees
  - name: messages
  - name: stores
